[package]
name = "wolfpacker"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.13.3", features = ["blocking", "json"]}
anyhow = "1.0.102"
indicatif = "0.18.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aws-sdk-s3 = "1"
aws-sdk-cloudfront = "1"
aws-config = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
walkdir = "2"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
dotenvy = "0.15"
rayon = "1"
toml = "0.8"
toml_edit = "0.22"

[build-dependencies]
embed-resource = "3"

